In [27]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd

In [2]:
url = requests.get('https://www.terra.com.br/esportes/futebol/brasileiro-serie-a/tabela/')
url_soup = soup(url.text, 'html.parser')

In [17]:
#Encontrei os HEADERS primeiro para usá-los como colunas
tabela = url_soup.find('thead')
tabela

<thead><tr><th class="main no-handler" colspan="4">Times</th><th class="desc points"><a href="#" name="Pontos" title="Pontos">P<span class="arrow"></span></a></th><th class="games"><a href="#" name="Jogos" title="Jogos">J<span class="arrow"></span></a></th><th class="victories"><a href="#" name="Vit%C3%B3rias" title="Vitórias">V<span class="arrow"></span></a></th><th class="draws"><a href="#" name="Empates" title="Empates">E<span class="arrow"></span></a></th><th class="lostgames"><a href="#" name="Derrotas" title="Derrotas">D<span class="arrow"></span></a></th><th class="goalspro"><a href="#" name="Gols%20Pr%C3%B3" title="Gols Pró">GP<span class="arrow"></span></a></th><th class="goalsagaints"><a href="#" name="Gols%20Contra" title="Gols Contra">GC<span class="arrow"></span></a></th><th class="goalsdifference"><a href="#" name="Saldo%20de%20Gols" title="Saldo de Gols">SG<span class="arrow"></span></a></th><th class="effectiveness"><a href="#" name="Aproveitamento" title="Aproveitamento">%<span class="arrow"></span></a></th></tr></thead>

In [23]:
#Criei uma lista para armazená-los, usei o for loop para fazer isso mais rápido
#Note que usei o .text em cada item para que retorne somente os valores que são escritos (strings)
headers = []
for i in tabela.find_all('th'):
    header = i.text
    headers.append(header)
headers

['Times', 'P', 'J', 'V', 'E', 'D', 'GP', 'GC', 'SG', '%']

In [30]:
#Criei o dataframe para segurar as colunas e me certificar que está tudo certo.
df = pd.DataFrame(columns = headers)
df

Empty DataFrame
Columns: [Times, P, J, V, E, D, GP, GC, SG, %]
Index: []

In [75]:
#Encontrei o resto das informações e eliminei os itens que ficariam em branco e/ou desnecessários
#Dessa vez precisei fazer dois for loop. No valor 'tr' estava a row inteira de cada time.
#O 'td' esvava separado pelos atributos das colunas. (P J V E D GP GC SG %)
#Usei o for loop novamente para colocá-los um por um em uma lista e depois colocar no dataframe.
#Mais uma vez, usei o .text para que retorne somente as strings e o .strip() para remover os espaços

info_t = []
for row in times_p.find_all('tr'):
    infos = row.find_all('td')
    infos_raw = [td.text.strip() for td in infos]
    del infos_raw[0]
    del infos_raw[0]
    del infos_raw[1]
    info_t.append(infos_raw)
print(info_t)

[['Atlético-MG >>', '56', '25', '17', '5', '3', '41', '17', '24', '74'], ['Flamengo >>', '45', '23', '14', '3', '6', '46', '21', '25', '65'], ['Fortaleza EC', '43', '27', '12', '7', '8', '34', '30', '4', '53'], ['Bragantino >>', '41', '25', '10', '11', '4', '40', '29', '11', '54'], ['Palmeiras >>', '40', '25', '12', '4', '9', '37', '32', '5', '53'], ['Corinthians >>', '40', '26', '10', '10', '6', '28', '23', '5', '51'], ['Internacional >>', '39', '25', '10', '9', '6', '34', '26', '8', '52'], ['Athletico-PR >>', '34', '25', '10', '4', '11', '32', '32', '0', '45'], ['Cuiabá >>', '34', '26', '7', '13', '6', '26', '26', '0', '43'], ['Fluminense >>', '33', '25', '8', '9', '8', '24', '27', '-3', '44'], ['Atlético Goianiense >>', '31', '25', '7', '10', '8', '20', '23', '-3', '41'], ['América-MG >>', '31', '26', '7', '10', '9', '25', '29', '-4', '39'], ['São Paulo >>', '31', '26', '6', '13', '7', '21', '26', '-5', '39'], ['Ceará >>', '30', '24', '6', '12', '6', '22', '25', '-3', '41'], ['Juventude >>', '28', '26', '6', '10', '10', '25', '33', '-8', '35'], ['Santos >>', '28', '25', '6', '10', '9', '23', '32', '-9', '37'], ['Bahia >>', '27', '25', '7', '6', '12', '28', '38', '-10', '36'], ['Sport >>', '26', '26', '6', '8', '12', '14', '22', '-8', '33'], ['Grêmio >>', '23', '24', '6', '5', '13', '20', '28', '-8', '31'], ['Chapecoense >>', '14', '27', '1', '11', '15', '24', '45', '-21', '17']]

In [80]:
df2 = pd.DataFrame(info_t, columns = headers)
df2

                     Times   P   J   V   E   D  GP  GC   SG   %
0           Atlético-MG >>  56  25  17   5   3  41  17   24  74
1              Flamengo >>  45  23  14   3   6  46  21   25  65
2             Fortaleza EC  43  27  12   7   8  34  30    4  53
3            Bragantino >>  41  25  10  11   4  40  29   11  54
4             Palmeiras >>  40  25  12   4   9  37  32    5  53
5           Corinthians >>  40  26  10  10   6  28  23    5  51
6         Internacional >>  39  25  10   9   6  34  26    8  52
7          Athletico-PR >>  34  25  10   4  11  32  32    0  45
8                Cuiabá >>  34  26   7  13   6  26  26    0  43
9            Fluminense >>  33  25   8   9   8  24  27   -3  44
10  Atlético Goianiense >>  31  25   7  10   8  20  23   -3  41
11           América-MG >>  31  26   7  10   9  25  29   -4  39
12            São Paulo >>  31  26   6  13   7  21  26   -5  39
13                Ceará >>  30  24   6  12   6  22  25   -3  41
14            Juventude >>  28  26   6  10  10  25  33   -8  35
15               Santos >>  28  25   6  10   9  23  32   -9  37
16                Bahia >>  27  25   7   6  12  28  38  -10  36
17                Sport >>  26  26   6   8  12  14  22   -8  33
18               Grêmio >>  23  24   6   5  13  20  28   -8  31
19          Chapecoense >>  14  27   1  11  15  24  45  -21  17

<b>AGORA TENHO QUE CRIAR UMA FUNÇÃO QUE EXECUTE ESSE SCRIPT
    & SALVAR O DATAFRAME NUM ARQUIVO CSV